

FROM continuumio/miniconda:4.7.12

ADD shiny/dependencies.R /dependencies.R
ADD shiny/majortom.yml /
RUN conda env create -f /majortom.yml && conda clean -a

ENV PATH /opt/conda/envs/majortom/bin:$PATH

RUN Rscript /dependencies.R

RUN apt install -y libcairo2

ADD shiny /shiny
ENV SATCAT_META /shiny/majortom

WORKDIR /shiny/majortom
CMD Rscript app.R
