

FROM continuumio/miniconda:4.7.12

# RUN mkdir /mylibs
# ENV R_LIBS /mylibs
ADD shiny/dependencies.R /dependencies.R
ADD shiny/majortom.yml /
RUN conda env create -f /majortom.yml && conda clean -a

RUN conda init
ENV PATH /opt/conda/envs/majortom/bin:$PATH

RUN conda activate majortom && Rscript /dependencies.R

ADD shiny /shiny

WORKDIR /shiny/majortom
CMD Rscript app.R
